In [6]:
import numpy as np
import pandas as pd

CSV,Excel,JSON,API,TXT

In [4]:
students={
    "Name":['Rohan','Aman','Krish','Neha'],
    "Age":[23,22,34,12],
    'Marks':[45,55,45,43]
}

In [7]:
df = pd.DataFrame(students)

In [11]:
df.ndim

2

In [12]:
age = [23,22,34,12]

pd.Series(age).ndim

1

In [13]:
data = pd.read_csv("realworld_sales_dataset.csv")

In [16]:
len(data)

2000

In [32]:
data.head()

,OrderID,OrderDate,ShipmentDate,CustomerName,Category,Region,Channel,Quantity,UnitPrice,DiscountApplied,SalesAmount
0,1152,2024-07-27,2024-08-04,Customer_327,Electronics,West,Wholesale,15,271.72,True,3668.220
1,500,2024-02-23,2024-03-04,Customer_426,Electronics,North,Online,17,433.52,False,7369.840
2,1337,2022-04-27,2022-05-06,Customer_379,Electronics,East,Retail,6,434.97,False,2609.820
3,1033,2022-02-24,2022-03-02,Customer_381,Food,West,Wholesale,12,283.51,True,3061.908
4,281,2023-11-16,2023-11-19,Customer_208,Furniture,South,Retail,15,49.16,True,663.660

In [31]:
data.tail(5)

,OrderID,OrderDate,ShipmentDate,CustomerName,Category,Region,Channel,Quantity,UnitPrice,DiscountApplied,SalesAmount
1995,894,2022-06-05,2022-06-08,Customer_247,Furniture,South,Wholesale,6,248.45,False,1490.700
1996,1837,2024-03-30,2024-04-08,Customer_427,Food,North,Wholesale,16,194.62,True,2802.528
1997,1702,2023-06-01,2023-06-07,Customer_135,Furniture,East,Online,6,118.02,False,708.120
1998,957,2024-02-14,2024-02-19,Customer_64,Furniture,West,Online,6,487.15,True,2630.610
1999,939,2024-12-13,2024-12-22,Customer_25,Electronics,North,Wholesale,14,136.99,False,1917.860

In [27]:
data['Category'].unique()

<ArrowStringArray>
['Electronics', 'Food', 'Furniture', 'Clothing']
Length: 4, dtype: str

In [33]:
data.iloc[0:3,4:7]

      Category Region    Channel
0  Electronics   West  Wholesale
1  Electronics  North     Online
2  Electronics   East     Retail

In [37]:
data.loc[0:4,'OrderID':'Category'].transpose()

,0,1,2,3,4
OrderID,1152,500,1337,1033,281
OrderDate,2024-07-27,2024-02-23,2022-04-27,2022-02-24,2023-11-16
ShipmentDate,2024-08-04,2024-03-04,2022-05-06,2022-03-02,2023-11-19
CustomerName,Customer_327,Customer_426,Customer_379,Customer_381,Customer_208
Category,Electronics,Electronics,Electronics,Food,Furniture

In [39]:
data['CostAmount'] = data['Quantity']*data['UnitPrice']

In [40]:
data.head()

,OrderID,OrderDate,ShipmentDate,CustomerName,Category,Region,Channel,Quantity,UnitPrice,DiscountApplied,SalesAmount,CostAmount
0,1152,2024-07-27,2024-08-04,Customer_327,Electronics,West,Wholesale,15,271.72,True,3668.220,4075.80
1,500,2024-02-23,2024-03-04,Customer_426,Electronics,North,Online,17,433.52,False,7369.840,7369.84
2,1337,2022-04-27,2022-05-06,Customer_379,Electronics,East,Retail,6,434.97,False,2609.820,2609.82
3,1033,2022-02-24,2022-03-02,Customer_381,Food,West,Wholesale,12,283.51,True,3061.908,3402.12
4,281,2023-11-16,2023-11-19,Customer_208,Furniture,South,Retail,15,49.16,True,663.660,737.40

In [43]:
data.sort_values(['Quantity','UnitPrice'],ascending=False)

,OrderID,OrderDate,ShipmentDate,CustomerName,Category,Region,Channel,Quantity,UnitPrice,DiscountApplied,SalesAmount,CostAmount
1778,805,2022-06-06,2022-06-14,Customer_352,Electronics,West,Retail,19,488.32,True,8350.272,9278.08
1086,938,2022-11-24,2022-12-02,Customer_425,Furniture,North,Wholesale,19,486.56,True,8320.176,9244.64
685,1330,2023-03-31,2023-04-04,Customer_261,Furniture,East,Retail,19,483.37,True,8265.627,9184.03
1824,1027,2022-01-11,2022-01-17,Customer_270,Clothing,West,Retail,19,476.79,False,9059.010,9059.01
1069,1298,2024-11-11,2024-11-15,Customer_365,Furniture,East,Wholesale,19,471.46,False,8957.740,8957.74
...,...,...,...,...,...,...,...,...,...,...,...,...
1218,579,2024-09-16,2024-09-17,Customer_214,Food,West,Retail,1,20.87,False,20.870,20.87
493,1321,2022-12-15,2022-12-21,Customer_288,Clothing,East,Wholesale,1,17.69,False,17.690,17.69
1397,287,2024-08-29,2024-09-04,Customer_72,Clothing,West,Wholesale,1,12.41,True,11.169,12.41
1904,1405,2024-06-27,2024-07-01,Customer_435,Food,South,Wholesale,1,7.83,False,7.830,7.83
72,428,2024-04-30,2024-05-04,Customer_273,Clothing,East,Online,1,6.55,False,6.550,6.55

In [49]:
data.groupby(['Category','Region'])[['SalesAmount','Quantity']].sum()

                    SalesAmount  Quantity
Category    Region
Clothing    East     330373.499      1431
            North    289477.314      1251
            South    314403.655      1332
            West     350246.180      1375
Electronics East     360818.577      1442
            North    301370.412      1216
            South    316755.458      1278
            West     338547.522      1363
Food        East     250346.189      1124
            North    296408.627      1237
            South    302344.959      1364
            West     271111.789      1094
Furniture   East     262142.428      1081
            North    328052.310      1243
            South    356538.774      1466
            West     248942.971      1094

In [51]:
data.groupby(['Region','Category'])[['SalesAmount','Quantity']].agg(['sum','mean','count'])

                   SalesAmount                    Quantity
                           sum         mean count      sum       mean count
Region Category
East   Clothing     330373.499  2359.810707   140     1431  10.221429   140
       Electronics  360818.577  2488.403979   145     1442   9.944828   145
       Food         250346.189  2296.754028   109     1124  10.311927   109
       Furniture    262142.428  2427.244704   108     1081  10.009259   108
North  Clothing     289477.314  2412.310950   120     1251  10.425000   120
       Electronics  301370.412  2666.994796   113     1216  10.761062   113
       Food         296408.627  2371.269016   125     1237   9.896000   125
       Furniture    328052.310  2645.583145   124     1243  10.024194   124
South  Clothing     314403.655  2346.295933   134     1332   9.940299   134
       Electronics  316755.458  2554.479500   124     1278  10.306452   124
       Food         302344.959  2190.905500   138     1364   9.884058   138
       Furniture    356538.774  2621.608632   136     1466  10.779412   136
West   Clothing     350246.180  2694.201385   130     1375  10.576923   130
       Electronics  338547.522  2665.728520   127     1363  10.732283   127
       Food         271111.789  2337.170595   116     1094   9.431034   116
       Furniture    248942.971  2242.729468   111     1094   9.855856   111

In [55]:
brief = data.pivot_table(values=['SalesAmount','Quantity'],columns=['Region','Channel'],index='Category')

In [57]:
brief.to_excel("xyz.xlsx")

In [59]:
data.isnull().sum()

OrderID            0
OrderDate          0
ShipmentDate       0
CustomerName       0
Category           0
Region             0
Channel            0
Quantity           0
UnitPrice          0
DiscountApplied    0
SalesAmount        0
CostAmount         0
dtype: int64

In [62]:
students={
    "Name":['Rohan','Aman','Krish','Neha'],
    "Age":[23,np.nan,34,np.nan],
    'Marks':[None,55,45,None]
}

df = pd.DataFrame(students)

In [63]:
df

    Name   Age  Marks
0  Rohan  23.0    NaN
1   Aman   NaN   55.0
2  Krish  34.0   45.0
3   Neha   NaN    NaN

In [67]:
df.isnull().mean()*100

Name      0.0
Age      50.0
Marks    50.0
dtype: float64

In [83]:
employees = pd.read_excel("hr_multi_sheet_dataset.xlsx",sheet_name='Employees')
departments =pd.read_excel("hr_multi_sheet_dataset.xlsx",sheet_name='Departments')
locations = pd.read_excel("hr_multi_sheet_dataset.xlsx",sheet_name='Locations')
jobs = pd.read_excel("hr_multi_sheet_dataset.xlsx",sheet_name='Jobs')
attendance = pd.read_excel("hr_multi_sheet_dataset.xlsx",sheet_name='Attendance')
attrition = pd.read_excel("hr_multi_sheet_dataset.xlsx",sheet_name='Attrition')

In [84]:
employees.head()

,EmployeeID,EmpCode,DeptID,LocationID,JobID,HireDate,Age,Gender,EmploymentStatus,Salary,PerformanceRating,TrainingHours,AbsenteeismDays,OvertimeHours,EngagementScore,SatisfactionScore,YearsSincePromotion,Bonus,ManagerID
0,1,E0001,6,1,1,2021-01-31,36,Male,Active,644704,1,8,5,24,90.3,3.4,0,46893,19
1,2,E0002,4,1,1,2019-01-19,34,Male,Active,742129,1,8,8,13,78.5,3.2,1,50055,23
2,3,E0003,6,4,4,2023-01-14,58,Female,Active,921776,1,2,0,0,65.3,2.8,5,80027,14
3,4,E0004,3,3,3,2020-05-31,42,Male,Active,368277,1,5,1,32,69.3,3.7,6,967,12
4,5,E0005,5,3,1,2026-03-08,50,Male,On Leave,551005,4,1,6,6,76.5,3.1,4,38246,10

In [81]:
departments

   DeptID  Department  Budget_USD  Headcount_Target
0       1          HR      300000                25
1       2     Finance      500000                30
2       3          IT      900000                60
3       4       Sales      700000                55
4       5   Marketing      450000                28
5       6  Operations      650000                40

In [73]:
locations.head()

   LocationID     City      State Region
0           1    Noida         UP  North
1           2  Lucknow         UP  North
2           3    Delhi      Delhi  North
3           4   Jaipur  Rajasthan   West

In [82]:
departments[['DeptID','Department']]

   DeptID  Department
0       1          HR
1       2     Finance
2       3          IT
3       4       Sales
4       5   Marketing
5       6  Operations

In [87]:
df = employees.merge(departments[['DeptID','Department']],how='left',on='DeptID')

In [86]:
dept_mapping = {
    "HR":"Human Resources",
    "Finance":"Finance Team",
    "IT":"Information Technology",
    "Sales":"Sales Team",
    "Marketing":"Marketing Team",
    "Operations":"Operation Team"
}

In [90]:
df['Department'] = df["Department"].map(dept_mapping)

In [91]:
df.head(10)

,EmployeeID,EmpCode,DeptID,LocationID,JobID,HireDate,Age,Gender,EmploymentStatus,Salary,...,TrainingHours,AbsenteeismDays,OvertimeHours,EngagementScore,SatisfactionScore,YearsSincePromotion,Bonus,ManagerID,Department,Department_map
0,1,E0001,6,1,1,2021-01-31,36,Male,Active,644704,...,8,5,24,90.3,3.4,0,46893,19,Operation Team,Operation Team
1,2,E0002,4,1,1,2019-01-19,34,Male,Active,742129,...,8,8,13,78.5,3.2,1,50055,23,Sales Team,Sales Team
2,3,E0003,6,4,4,2023-01-14,58,Female,Active,921776,...,2,0,0,65.3,2.8,5,80027,14,Operation Team,Operation Team
3,4,E0004,3,3,3,2020-05-31,42,Male,Active,368277,...,5,1,32,69.3,3.7,6,967,12,Information Technology,Information Technology
4,5,E0005,5,3,1,2026-03-08,50,Male,On Leave,551005,...,1,6,6,76.5,3.1,4,38246,10,Marketing Team,Marketing Team
5,6,E0006,6,3,4,2025-11-25,25,Male,Active,845846,...,1,11,17,59.3,4.3,6,43250,8,Operation Team,Operation Team
6,7,E0007,1,4,5,2023-02-01,44,Male,Active,818797,...,4,0,4,74.4,4.2,5,68931,22,Human Resources,Human Resources
7,8,E0008,6,1,3,2023-12-28,36,Male,Active,439591,...,8,5,3,63.4,3.2,1,56309,22,Operation Team,Operation Team
8,9,E0009,3,1,4,2018-05-12,41,Female,Active,930925,...,5,0,21,67.4,3.1,1,86707,21,Information Technology,Information Technology
9,10,E0010,4,4,8,2019-08-09,37,Male,Active,272789,...,8,8,9,68.3,3.9,2,41334,24,Sales Team,Sales Team