In [1]:
import numpy as np
import pandas as pd

<h2>Datastructure in pandas</h2>

- Series
- Dataframe

CSV,Excel,JSON,API,TXT

In [2]:
students={
    "Name":['Rohan','Aman','Krish','Neha'],
    "Age":[23,22,34,12],
    'Marks':[45,55,45,43]
}

In [3]:
type(students)

dict

In [5]:
df = pd.DataFrame(students)

In [8]:
arr = [[2,3,4],
 [4,5,3],
 [4,9,0]]

In [9]:
df = pd.DataFrame(arr,columns=['ColA','ColB','ColC'])

In [16]:
df

   ColA  ColB  ColC
0     2     3     4
1     4     5     3
2     4     9     0

In [21]:
df['ColB']

0    3
1    5
2    9
Name: ColB, dtype: int64

In [11]:
df.ndim

2

In [19]:
age = [23,22,34,12]

pd.Series(age,name="Age")

0    23
1    22
2    34
3    12
Name: Age, dtype: int64

In [25]:
data = pd.read_csv("realworld_sales_dataset.csv")

In [26]:
len(data)

2000

In [28]:
data.head(20)

,OrderID,OrderDate,ShipmentDate,CustomerName,Category,Region,Channel,Quantity,UnitPrice,DiscountApplied,SalesAmount
0,1152,2024-07-27,2024-08-04,Customer_327,Electronics,West,Wholesale,15,271.72,True,3668.220
1,500,2024-02-23,2024-03-04,Customer_426,Electronics,North,Online,17,433.52,False,7369.840
2,1337,2022-04-27,2022-05-06,Customer_379,Electronics,East,Retail,6,434.97,False,2609.820
3,1033,2022-02-24,2022-03-02,Customer_381,Food,West,Wholesale,12,283.51,True,3061.908
4,281,2023-11-16,2023-11-19,Customer_208,Furniture,South,Retail,15,49.16,True,663.660
5,1659,2022-05-26,2022-06-01,Customer_237,Clothing,South,Wholesale,6,167.90,False,1007.400
6,1329,2022-07-25,2022-07-28,Customer_98,Food,West,Retail,13,255.81,False,3325.530
7,211,2024-04-01,2024-04-02,Customer_271,Clothing,South,Retail,19,111.47,False,2117.930
8,1261,2022-07-11,2022-07-14,Customer_359,Electronics,East,Wholesale,6,295.84,False,1775.040
9,1910,2024-07-28,2024-08-03,Customer_233,Electronics,North,Online,17,156.16,True,2389.248
10,189,2022-01-02,2022-01-09,Customer_247,Electronics,West,Wholesale,19,216.32,False,4110.080
11,1950,2024-02-06,2024-02-16,Customer_496,Food,West,Online,5,54.84,True,246.780
12,617,2022-02-12,2022-02-21,Customer_242,Clothing,North,Online,11,445.88,False,4904.680
13,1823,2024-12-15,2024-12-18,Customer_465,Furniture,East,Wholesale,9,419.28,False,3773.520
14,1771,2023-08-17,2023-08-20,Customer_35,Electronics,North,Retail,11,144.42,True,1429.758
15,241,2024-12-08,2024-12-09,Customer_295,Furniture,North,Wholesale,18,397.27,True,6435.774
16,719,2024-07-08,2024-07-14,Customer_310,Electronics,West,Retail,19,14.14,False,268.660
17,345,2024-12-06,2024-12-15,Customer_315,Furniture,East,Retail,6,324.75,False,1948.500
18,1343,2022-03-13,2022-03-21,Customer_287,Electronics,West,Online,18,469.22,True,7601.364
19,452,2022-06-19,2022-06-25,Customer_344,Clothing,West,Wholesale,18,379.57,True,6149.034

In [30]:
data.tail(20)

,OrderID,OrderDate,ShipmentDate,CustomerName,Category,Region,Channel,Quantity,UnitPrice,DiscountApplied,SalesAmount
1980,885,2023-10-26,2023-11-01,Customer_416,Food,North,Retail,11,443.76,False,4881.360
1981,919,2024-10-06,2024-10-08,Customer_256,Electronics,East,Online,13,391.57,False,5090.410
1982,78,2023-10-10,2023-10-17,Customer_212,Clothing,East,Wholesale,16,71.30,False,1140.800
1983,1675,2023-08-13,2023-08-17,Customer_33,Furniture,East,Online,12,363.28,True,3923.424
1984,999,2022-02-11,2022-02-20,Customer_63,Clothing,North,Online,14,399.17,True,5029.542
1985,703,2022-11-11,2022-11-16,Customer_90,Food,North,Wholesale,4,19.09,False,76.360
1986,181,2023-04-18,2023-04-22,Customer_355,Furniture,East,Online,17,146.33,False,2487.610
1987,891,2024-09-29,2024-10-08,Customer_468,Clothing,West,Online,14,255.14,True,3214.764
1988,249,2022-10-07,2022-10-17,Customer_365,Food,East,Online,14,114.72,False,1606.080
1989,933,2024-10-28,2024-11-03,Customer_494,Food,South,Online,10,230.69,True,2076.210
1990,1694,2023-10-10,2023-10-11,Customer_258,Electronics,North,Wholesale,18,470.86,True,7627.932
1991,371,2024-06-14,2024-06-17,Customer_269,Clothing,West,Retail,7,33.79,False,236.530
1992,1304,2024-05-18,2024-05-23,Customer_149,Furniture,South,Wholesale,11,299.98,True,2969.802
1993,1450,2024-06-29,2024-07-07,Customer_137,Electronics,North,Online,11,430.08,True,4257.792
1994,435,2024-06-09,2024-06-16,Customer_407,Furniture,North,Retail,8,469.60,False,3756.800
1995,894,2022-06-05,2022-06-08,Customer_247,Furniture,South,Wholesale,6,248.45,False,1490.700
1996,1837,2024-03-30,2024-04-08,Customer_427,Food,North,Wholesale,16,194.62,True,2802.528
1997,1702,2023-06-01,2023-06-07,Customer_135,Furniture,East,Online,6,118.02,False,708.120
1998,957,2024-02-14,2024-02-19,Customer_64,Furniture,West,Online,6,487.15,True,2630.610
1999,939,2024-12-13,2024-12-22,Customer_25,Electronics,North,Wholesale,14,136.99,False,1917.860

In [35]:
data['Category'].nunique()

4

In [44]:
data.iloc[0:4,1:6]

    OrderDate ShipmentDate  CustomerName     Category Region
0  2024-07-27   2024-08-04  Customer_327  Electronics   West
1  2024-02-23   2024-03-04  Customer_426  Electronics  North
2  2022-04-27   2022-05-06  Customer_379  Electronics   East
3  2022-02-24   2022-03-02  Customer_381         Food   West

In [46]:
data.loc[0:4,'OrderID':'Category']

   OrderID   OrderDate ShipmentDate  CustomerName     Category
0     1152  2024-07-27   2024-08-04  Customer_327  Electronics
1      500  2024-02-23   2024-03-04  Customer_426  Electronics
2     1337  2022-04-27   2022-05-06  Customer_379  Electronics
3     1033  2022-02-24   2022-03-02  Customer_381         Food
4      281  2023-11-16   2023-11-19  Customer_208    Furniture

In [47]:
data['CostAmount'] = data['Quantity']*data['UnitPrice']

In [48]:
data.head()

,OrderID,OrderDate,ShipmentDate,CustomerName,Category,Region,Channel,Quantity,UnitPrice,DiscountApplied,SalesAmount,CostAmount
0,1152,2024-07-27,2024-08-04,Customer_327,Electronics,West,Wholesale,15,271.72,True,3668.220,4075.80
1,500,2024-02-23,2024-03-04,Customer_426,Electronics,North,Online,17,433.52,False,7369.840,7369.84
2,1337,2022-04-27,2022-05-06,Customer_379,Electronics,East,Retail,6,434.97,False,2609.820,2609.82
3,1033,2022-02-24,2022-03-02,Customer_381,Food,West,Wholesale,12,283.51,True,3061.908,3402.12
4,281,2023-11-16,2023-11-19,Customer_208,Furniture,South,Retail,15,49.16,True,663.660,737.40

In [55]:
data.sort_values(['Quantity','UnitPrice'],ascending=True).head(50)

,OrderID,OrderDate,ShipmentDate,CustomerName,Category,Region,Channel,Quantity,UnitPrice,DiscountApplied,SalesAmount,CostAmount
72,428,2024-04-30,2024-05-04,Customer_273,Clothing,East,Online,1,6.55,False,6.550,6.55
1904,1405,2024-06-27,2024-07-01,Customer_435,Food,South,Wholesale,1,7.83,False,7.830,7.83
1397,287,2024-08-29,2024-09-04,Customer_72,Clothing,West,Wholesale,1,12.41,True,11.169,12.41
493,1321,2022-12-15,2022-12-21,Customer_288,Clothing,East,Wholesale,1,17.69,False,17.690,17.69
1218,579,2024-09-16,2024-09-17,Customer_214,Food,West,Retail,1,20.87,False,20.870,20.87
1820,42,2023-07-19,2023-07-25,Customer_75,Electronics,East,Retail,1,21.55,True,19.395,21.55
1160,1482,2022-09-27,2022-10-05,Customer_328,Furniture,South,Wholesale,1,26.29,True,23.661,26.29
30,1568,2023-12-12,2023-12-13,Customer_217,Furniture,South,Wholesale,1,27.55,True,24.795,27.55
204,436,2023-07-23,2023-07-29,Customer_56,Electronics,West,Retail,1,31.68,False,31.680,31.68
429,850,2024-06-06,2024-06-15,Customer_494,Food,East,Online,1,40.81,True,36.729,40.81
519,1410,2023-11-26,2023-11-28,Customer_197,Furniture,South,Online,1,42.98,True,38.682,42.98
203,1,2024-05-10,2024-05-12,Customer_143,Clothing,North,Online,1,48.82,False,48.820,48.82
162,768,2024-07-06,2024-07-12,Customer_163,Furniture,North,Retail,1,48.87,True,43.983,48.87
292,1032,2022-04-08,2022-04-13,Customer_124,Electronics,East,Online,1,49.71,False,49.710,49.71
1810,1051,2022-02-11,2022-02-21,Customer_148,Electronics,South,Retail,1,56.89,False,56.890,56.89
73,1357,2024-12-05,2024-12-11,Customer_291,Food,North,Retail,1,58.53,True,52.677,58.53
1527,1822,2023-11-21,2023-12-01,Customer_345,Food,West,Wholesale,1,61.75,False,61.750,61.75
821,489,2024-03-25,2024-03-28,Customer_188,Electronics,North,Retail,1,66.68,False,66.680,66.68
1927,1961,2023-06-06,2023-06-16,Customer_232,Electronics,East,Wholesale,1,71.03,True,63.927,71.03
1720,925,2024-04-10,2024-04-19,Customer_237,Clothing,South,Retail,1,80.61,True,72.549,80.61
1877,1544,2024-03-24,2024-03-29,Customer_35,Clothing,South,Wholesale,1,87.58,True,78.822,87.58
511,702,2023-11-23,2023-11-29,Customer_17,Furniture,South,Retail,1,87.76,False,87.760,87.76
1652,515,2023-05-17,2023-05-20,Customer_137,Food,East,Retail,1,92.64,True,83.376,92.64
1844,1195,2022-02-07,2022-02-12,Customer_30,Food,South,Retail,1,96.26,False,96.260,96.26
1776,723,2022-01-04,2022-01-13,Customer_415,Furniture,North,Wholesale,1,100.90,True,90.810,100.90
1074,130,2024-03-06,2024-03-07,Customer_236,Electronics,West,Wholesale,1,103.46,True,93.114,103.46
156,1274,2022-10-12,2022-10-16,Customer_332,Clothing,South,Online,1,105.22,False,105.220,105.22
891,1762,2023-02-10,2023-02-15,Customer_413,Electronics,North,Online,1,106.21,True,95.589,106.21
1681,1404,2022-03-28,2022-03-31,Customer_112,Electronics,South,Wholesale,1,118.85,True,106.965,118.85
184,978,2023-08-16,2023-08-20,Customer_239,Food,East,Wholesale,1,126.17,True,113.553,126.17
1860,1776,2022-03-14,2022-03-19,Customer_77,Electronics,North,Online,1,126.43,True,113.787,126.43
471,1177,2022-08-04,2022-08-05,Customer_296,Food,West,Retail,1,127.44,False,127.440,127.44
1133,147,2023-10-04,2023-10-14,Customer_125,Food,West,Wholesale,1,128.40,False,128.400,128.40
1962,799,2023-01-26,2023-01-28,Customer_400,Furniture,South,Online,1,133.00,True,119.700,133.00
1945,1764,2022-12-08,2022-12-16,Customer_367,Food,East,Retail,1,135.92,False,135.920,135.92
49,739,2023-06-16,2023-06-20,Customer_20,Furniture,South,Retail,1,137.02,False,137.020,137.02
918,145,2022-04-23,2022-04-27,Customer_49,Food,East,Online,1,147.23,False,147.230,147.23
735,1650,2022-06-01,2022-06-09,Customer_255,Food,North,Retail,1,158.37,True,142.533,158.37
1401,1631,2022-06-08,2022-06-16,Customer_304,Electronics,South,Online,1,158.42,True,142.578,158.42
1800,1437,2024-08-04,2024-08-13,Customer_43,Electronics,South,Wholesale,1,158.97,True,143.073,158.97
524,1356,2024-06-07,2024-06-17,Customer_212,Furniture,East,Wholesale,1,173.07,True,155.763,173.07
614,1068,2022-12-05,2022-12-14,Customer_34,Clothing,West,Retail,1,180.36,True,162.324,180.36
108,1858,2022-03-06,2022-03-11,Customer_480,Clothing,East,Wholesale,1,189.04,False,189.040,189.04
984,1752,2024-01-19,2024-01-27,Customer_42,Furniture,West,Online,1,191.53,True,172.377,191.53
1051,1377,2024-06-05,2024-06-11,Customer_75,Food,North,Online,1,196.71,False,196.710,196.71
1119,1256,2024-09-15,2024-09-23,Customer_12,Clothing,West,Online,1,206.89,True,186.201,206.89
1512,775,2022-03-19,2022-03-27,Customer_317,Electronics,North,Online,1,207.71,True,186.939,207.71
1142,444,2022-08-23,2022-08-27,Customer_499,Food,West,Retail,1,222.87,True,200.583,222.87
657,469,2023-10-15,2023-10-17,Customer_38,Electronics,South,Wholesale,1,224.41,True,201.969,224.41
179,1938,2024-07-09,2024-07-14,Customer_127,Food,West,Online,1,224.74,False,224.740,224.74

In [58]:
data.groupby(['Region','Channel'])[['SalesAmount','Quantity']].sum()

                  SalesAmount  Quantity
Region Channel
East   Online      438615.656      1955
       Retail      354040.629      1522
       Wholesale   411024.408      1601
North  Online      400304.334      1709
       Retail      410459.593      1729
       Wholesale   404544.736      1509
South  Online      510467.148      2129
       Retail      409360.994      1757
       Wholesale   370214.704      1554
West   Online      485926.269      1864
       Retail      335622.284      1518
       Wholesale   387299.909      1544

In [59]:
data.groupby(['Category','Region'])[['SalesAmount','Quantity']].sum()

                    SalesAmount  Quantity
Category    Region
Clothing    East     330373.499      1431
            North    289477.314      1251
            South    314403.655      1332
            West     350246.180      1375
Electronics East     360818.577      1442
            North    301370.412      1216
            South    316755.458      1278
            West     338547.522      1363
Food        East     250346.189      1124
            North    296408.627      1237
            South    302344.959      1364
            West     271111.789      1094
Furniture   East     262142.428      1081
            North    328052.310      1243
            South    356538.774      1466
            West     248942.971      1094

In [51]:
data.groupby(['Region','Category'])[['SalesAmount','Quantity']].agg(['sum','mean','count'])

                   SalesAmount                    Quantity
                           sum         mean count      sum       mean count
Region Category
East   Clothing     330373.499  2359.810707   140     1431  10.221429   140
       Electronics  360818.577  2488.403979   145     1442   9.944828   145
       Food         250346.189  2296.754028   109     1124  10.311927   109
       Furniture    262142.428  2427.244704   108     1081  10.009259   108
North  Clothing     289477.314  2412.310950   120     1251  10.425000   120
       Electronics  301370.412  2666.994796   113     1216  10.761062   113
       Food         296408.627  2371.269016   125     1237   9.896000   125
       Furniture    328052.310  2645.583145   124     1243  10.024194   124
South  Clothing     314403.655  2346.295933   134     1332   9.940299   134
       Electronics  316755.458  2554.479500   124     1278  10.306452   124
       Food         302344.959  2190.905500   138     1364   9.884058   138
       Furniture    356538.774  2621.608632   136     1466  10.779412   136
West   Clothing     350246.180  2694.201385   130     1375  10.576923   130
       Electronics  338547.522  2665.728520   127     1363  10.732283   127
       Food         271111.789  2337.170595   116     1094   9.431034   116
       Furniture    248942.971  2242.729468   111     1094   9.855856   111

In [62]:
brief = data.pivot_table(values=['SalesAmount'],columns=['Channel'],index='Category')

In [63]:
brief

             SalesAmount
Channel           Online       Retail    Wholesale
Category
Clothing     2638.808281  2321.052322  2379.597870
Electronics  2932.992860  2390.248887  2415.084316
Food         2211.212783  2118.604993  2583.668878
Furniture    2326.525314  2590.248778  2597.526424

In [60]:
brief = data.pivot_table(values=['SalesAmount','Quantity'],columns=['Region','Channel'],index='Category')

In [61]:
brief

              Quantity                                                         \
Region            East                            North
Channel         Online     Retail  Wholesale     Online     Retail  Wholesale
Category
Clothing     10.465517  10.583333   9.630435  10.702703  10.681818   9.871795
Electronics  10.720000   9.977273   9.156863  10.775000  10.270270  11.250000
Food         10.627907   9.424242  10.787879  10.042553  10.809524   8.638889
Furniture     9.861111  10.289474   9.852941  10.000000  10.625000   9.488372

                                                         ...  SalesAmount  \
Region           South                             West  ...         East
Channel         Online     Retail  Wholesale     Online  ...    Wholesale
Category                                                 ...
Clothing     11.214286  10.130435   8.586957  10.708333  ...  2250.216109
Electronics  11.581395   9.866667   9.333333  11.800000  ...  2380.839294
Food         10.186441   8.888889  10.676471   9.325000  ...  2666.908152
Furniture    10.960784  11.175000  10.222222   9.489362  ...  2884.814529

                                                                              \
Region             North                                  South
Channel           Online       Retail    Wholesale       Online       Retail
Category
Clothing     2531.911703  2240.779273  2492.366487  2915.777286  2224.861326
Electronics  2646.414450  2262.463108  3105.630528  3176.013140  2418.047378
Food         2272.292766  2519.255357  2327.837278  2042.184373  2002.084489
Furniture    2291.933244  3058.636125  2598.548884  2567.589392  2702.785975


Region                           West
Channel        Wholesale       Online       Retail    Wholesale
Category
Clothing     1947.769304  2876.612271  2293.795255  3070.491387
Electronics  1982.632250  3331.609311  2360.174971  2257.899042
Food         2698.890559  2354.333400  1875.091903  2640.235644
Furniture    2610.672800  2207.513298  2293.283657  2238.790276

[4 rows x 24 columns]

In [57]:
brief.to_excel("xyz.xlsx")

In [59]:
data.isnull().sum()

OrderID            0
OrderDate          0
ShipmentDate       0
CustomerName       0
Category           0
Region             0
Channel            0
Quantity           0
UnitPrice          0
DiscountApplied    0
SalesAmount        0
CostAmount         0
dtype: int64

In [64]:
students={
    "Name":['Rohan','Aman','Krish','Neha'],
    "Age":[23,np.nan,34,np.nan],
    'Marks':[None,55,45,None]
}

df = pd.DataFrame(students)

In [65]:
df

    Name   Age  Marks
0  Rohan  23.0    NaN
1   Aman   NaN   55.0
2  Krish  34.0   45.0
3   Neha   NaN    NaN

In [66]:
df.isnull().mean()*100

Name      0.0
Age      50.0
Marks    50.0
dtype: float64

In [22]:
employees = pd.read_excel("hr_multi_sheet_dataset.xlsx",sheet_name='Employees')
departments =pd.read_excel("hr_multi_sheet_dataset.xlsx",sheet_name='Departments')
locations = pd.read_excel("hr_multi_sheet_dataset.xlsx",sheet_name='Locations')
jobs = pd.read_excel("hr_multi_sheet_dataset.xlsx",sheet_name='Jobs')
attendance = pd.read_excel("hr_multi_sheet_dataset.xlsx",sheet_name='Attendance')
attrition = pd.read_excel("hr_multi_sheet_dataset.xlsx",sheet_name='Attrition')

In [23]:
employees.head()

,EmployeeID,EmpCode,DeptID,LocationID,JobID,HireDate,Age,Gender,EmploymentStatus,Salary,PerformanceRating,TrainingHours,AbsenteeismDays,OvertimeHours,EngagementScore,SatisfactionScore,YearsSincePromotion,Bonus,ManagerID
0,1,E0001,6,1,1,2021-01-31,36,Male,Active,644704,1,8,5,24,90.3,3.4,0,46893,19
1,2,E0002,4,1,1,2019-01-19,34,Male,Active,742129,1,8,8,13,78.5,3.2,1,50055,23
2,3,E0003,6,4,4,2023-01-14,58,Female,Active,921776,1,2,0,0,65.3,2.8,5,80027,14
3,4,E0004,3,3,3,2020-05-31,42,Male,Active,368277,1,5,1,32,69.3,3.7,6,967,12
4,5,E0005,5,3,1,2026-03-08,50,Male,On Leave,551005,4,1,6,6,76.5,3.1,4,38246,10

In [81]:
departments

   DeptID  Department  Budget_USD  Headcount_Target
0       1          HR      300000                25
1       2     Finance      500000                30
2       3          IT      900000                60
3       4       Sales      700000                55
4       5   Marketing      450000                28
5       6  Operations      650000                40

In [73]:
locations.head()

   LocationID     City      State Region
0           1    Noida         UP  North
1           2  Lucknow         UP  North
2           3    Delhi      Delhi  North
3           4   Jaipur  Rajasthan   West

In [82]:
departments[['DeptID','Department']]

   DeptID  Department
0       1          HR
1       2     Finance
2       3          IT
3       4       Sales
4       5   Marketing
5       6  Operations

In [67]:
df = employees.merge(departments[['DeptID','Department']],how='left',on='DeptID')

In [68]:
df

,EmployeeID,EmpCode,DeptID,LocationID,JobID,HireDate,Age,Gender,EmploymentStatus,Salary,PerformanceRating,TrainingHours,AbsenteeismDays,OvertimeHours,EngagementScore,SatisfactionScore,YearsSincePromotion,Bonus,ManagerID,Department
0,1,E0001,6,1,1,2021-01-31,36,Male,Active,644704,1,8,5,24,90.3,3.4,0,46893,19,Operations
1,2,E0002,4,1,1,2019-01-19,34,Male,Active,742129,1,8,8,13,78.5,3.2,1,50055,23,Sales
2,3,E0003,6,4,4,2023-01-14,58,Female,Active,921776,1,2,0,0,65.3,2.8,5,80027,14,Operations
3,4,E0004,3,3,3,2020-05-31,42,Male,Active,368277,1,5,1,32,69.3,3.7,6,967,12,IT
4,5,E0005,5,3,1,2026-03-08,50,Male,On Leave,551005,4,1,6,6,76.5,3.1,4,38246,10,Marketing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,226,E0226,1,3,7,2025-07-22,23,Male,Active,994689,5,8,0,23,81.1,3.1,1,27754,16,HR
226,227,E0227,2,3,5,2018-03-04,34,Male,On Leave,750837,1,7,7,3,74.2,3.6,1,71652,23,Finance
227,228,E0228,5,2,7,2020-09-07,56,Female,Active,1110762,4,7,3,29,70.1,3.6,4,70195,21,Marketing
228,229,E0229,3,3,5,2022-01-13,53,Female,Active,760104,4,5,3,16,92.5,2.5,1,28537,12,IT
229,230,E0230,3,4,1,2024-04-23,35,Male,Active,732405,5,6,5,11,84.5,3.1,2,95112,5,IT

In [69]:
dept_mapping = {
    "HR":"Human Resources",
    "Finance":"Finance Team",
    "IT":"Information Technology",
    "Sales":"Sales Team",
    "Marketing":"Marketing Team",
    "Operations":"Operation Team"
}

In [70]:
df['Department'] = df["Department"].map(dept_mapping)

In [71]:
df.head(10)

,EmployeeID,EmpCode,DeptID,LocationID,JobID,HireDate,Age,Gender,EmploymentStatus,Salary,PerformanceRating,TrainingHours,AbsenteeismDays,OvertimeHours,EngagementScore,SatisfactionScore,YearsSincePromotion,Bonus,ManagerID,Department
0,1,E0001,6,1,1,2021-01-31,36,Male,Active,644704,1,8,5,24,90.3,3.4,0,46893,19,Operation Team
1,2,E0002,4,1,1,2019-01-19,34,Male,Active,742129,1,8,8,13,78.5,3.2,1,50055,23,Sales Team
2,3,E0003,6,4,4,2023-01-14,58,Female,Active,921776,1,2,0,0,65.3,2.8,5,80027,14,Operation Team
3,4,E0004,3,3,3,2020-05-31,42,Male,Active,368277,1,5,1,32,69.3,3.7,6,967,12,Information Technology
4,5,E0005,5,3,1,2026-03-08,50,Male,On Leave,551005,4,1,6,6,76.5,3.1,4,38246,10,Marketing Team
5,6,E0006,6,3,4,2025-11-25,25,Male,Active,845846,3,1,11,17,59.3,4.3,6,43250,8,Operation Team
6,7,E0007,1,4,5,2023-02-01,44,Male,Active,818797,2,4,0,4,74.4,4.2,5,68931,22,Human Resources
7,8,E0008,6,1,3,2023-12-28,36,Male,Active,439591,3,8,5,3,63.4,3.2,1,56309,22,Operation Team
8,9,E0009,3,1,4,2018-05-12,41,Female,Active,930925,2,5,0,21,67.4,3.1,1,86707,21,Information Technology
9,10,E0010,4,4,8,2019-08-09,37,Male,Active,272789,5,8,8,9,68.3,3.9,2,41334,24,Sales Team